### ISSUE TITLE
Support processing yaml schema?

### ISSUE THREAD

**Issue by dennisroche** [jsontypedef/json-typedef-codegen#38]
Hi, 

In https://jsontypedef.com/docs/jtd-in-5-minutes/, it shows that you can write JSON Type Def in either JSON or YAML. 

```yaml
properties:
    name:
        type: string
    isAdmin:
        type: boolean
```

Does `json-typedef-codegen` support generating code from yaml schemas?
